services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: medianet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5433"
    command: postgres -p 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d medianet -p 5433" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .  # путь к папке с Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/medianet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    restart: on-failure

volumes:
  postgres_data: